import { Dimensions,StyleSheet } from 'react-native';
const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  modalBackground: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    width: '70%',
    height: '98%',
    backgroundColor: '#fff',
    // alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 5,
    elevation: 6,
    paddingBottom: 20,

  },
  scrollViewContent: {
    paddingBottom: 20,
    width: "100%"
  },
  modalTitleContainer: {
    flexDirection: 'row',
    backgroundColor: '#f4f6f8',
    width: '100%',
    padding: 10,
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#666',
  },
  CloseModel: {
    width: 30,
    height: 30,
    alignItems: "center",
    justifyContent: "center",

  },
  timerRow: {
    width: '100%',
    alignItems: 'flex-end',
    paddingHorizontal: 20,
    marginTop: 10,
  },
  timerWrapper: {
    backgroundColor: '#fff',
    borderWidth: 2,
    borderColor: '#5773A2',
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 14,
  },
  timerText: {
    color: '#5773A2',
    fontSize: 20,
    fontWeight: 'bold',
  },
  playerListRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginTop: 20,
  },
  circleItem: {
    padding: 20,
    borderWidth: 1,
    borderRadius: 30,
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  circleText: {
    fontSize: 16,
  },
  addMultipleBtn: {
    marginLeft: 10,
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#08c3f8',
  },
  addMultipleBtnText: {
    color: '#08c3f8',
    fontWeight: '600',
  },
  memberSection: {
    width: '100%',
    // alignItems: 'center',
    marginTop: 10,

  },
  Pluscontainer: {
    flexDirection: 'row',     
    justifyContent: 'center', 
    alignItems: 'center', 
    marginVertical:10,   
  },
  sectionNote: {
    color: '#000',
    fontFamily: 'SourceSansPro_SemiBold',
    textAlign: 'center',
  },
  plusCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderColor: '#08c3f8',
    borderWidth:1,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 4,
  },
  plusText: {
    color: '#08c3f8',
    fontSize: 18,
    justifyContent :'center',
    alignItems :'center',
    fontWeight: 'bold',
    // marginBottom :5

  },
  memberFieldWrapper: {
    width: '48%',
  // paddingHorizontal: 8,
  paddingVertical: 5,
  alignItems: 'center',
  },
  memberLabel: {
    color: '#000',
    fontFamily: 'SourceSansPro_SemiBold',
    textAlign: 'left',
    width: "60%",

  },
  memberCardsContainer:{
    
      width: "100%",
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "flex-start",
      paddingHorizontal: 20,
    
  },
  memberInputRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '60%',
    borderWidth: 1,
    borderRadius: 5,
    alignItems: 'center',
    height: 40,
    paddingHorizontal :5,
  },
  iconcontainer: {
    width: '25%',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  closeBtn: {
    marginTop: 30,
    backgroundColor: '#FF3B30',
    paddingVertical: 12,
    paddingHorizontal: 30,
    borderRadius: 10,
  },
  comments: {
    width: '100%',
    maxHeight: 100,
    borderWidth: 1,
    borderRadius: 5,
    paddingHorizontal: 10,
    paddingVertical: 25,
  },
  commentsBox: { height: 110, borderColor: "#cbcbcb", borderRadius: 5, padding: 10, borderWidth: 1, zIndex : -1 },
  commentTxt: { fontFamily: "SourceSansPro_SemiBoldItalic", fontSize: 20, color: "#515659", padding: 5 },
  SubmitContainer:{
     width: "100%", alignItems: "center" 
  },
  SubmitBtn: {
    borderWidth: 2,
    borderColor: "#5773A2",
    paddingHorizontal: 30,
    paddingVertical: 5,
    borderRadius: 20,
  },
  submitTxt: {
    fontSize: 18,
    fontFamily: "SourceSansPro_SemiBold",
    color: "#5773A2",
  },
  txt1: {
    color: "#08c3f8",
    fontSize: 18,
    fontFamily: "SourceSansPro_SemiBold",
    textAlign: "center",
    marginTop: 30,
    marginBottom: 10,
  },
  txt2: {
    color: "#666",
    fontFamily: "SourceSansPro_SemiBold",
    fontSize: 18,
    textAlign: "center",
  },
  MemberTxt:{
    width: "70%" , paddingHorizontal :8
  },
  popupContainer: {
    position: 'absolute',
    backgroundColor: '#fff',
    elevation: 3,
    padding: 5,
    width: 100,
    marginHorizontal :30,
    right :-50,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 5,
  },
  MutiplepopupContainer: {
    position: 'absolute',
    backgroundColor: '#fff',
    elevation: 3,
    padding: 5,
    width: 100,
    marginHorizontal :30,
    top:0,
    right :80,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 5,
  },
  popupButton: {
    paddingVertical: 5,
  },
  popupButtonText: {
    fontFamily:'SourceSansPro_SemiBold',
    fontSize :16,
    color: '#08c3f8',
    textAlign: 'center',
  },
  modalHeader: {
    alignItems: "center",
    paddingVertical: 20,
  },
  closeIcon: {
    width: 30,
    height: 30,
    position: "absolute",
    right: 10,
    top: 10,
  },
  searchRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    width: "50%",
    gap: 10,
  },
  input: {
    borderWidth: 1,
    borderColor: "#ccc",
    padding: 8,
    borderRadius: 5,
    flexGrow: 1,
    minWidth: '35%',
  },
  searchButton: {
    borderWidth: 1,
    borderColor: "#5773A2",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 6,
    paddingHorizontal: 20,
    borderRadius: 20,
    marginLeft: 5,
  },
  clearButton: {
    borderWidth: 1,
    borderColor: "#5773A2",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 6,
    paddingHorizontal: 20,
    borderRadius: 20,
    marginLeft: 5,
  },
  searchClearButtonText: {
    fontSize:18,
    color: "#5773A2",
    fontWeight: '600',
  },
  checkboxButton: {
    flexDirection: "row",
    alignItems: "center",
    marginLeft: 10,
    marginTop: 10,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderWidth: 2,
    borderColor: "#5773A2",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 5,
  },
  });