import { isPlatformAndroid } from "@/components/constants/Matrices";
import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    paddingHorizontal: 10,
    marginTop: 50,
    backgroundColor: "#fff",
    paddingBottom: 100,
  },
  headerTitle: {
    width: "100%",
    alignItems: "flex-start",
    paddingLeft: 0,
    bottom: 1,
  },
  headerText: {
    fontSize: 20,
    color: "#000",
    marginLeft: 12,
  },
  menuTitle: {
    fontSize: 22,
    color: "#4B5154",
    fontFamily: "SourceSansPro_SemiBold",
    paddingTop: 20,
    lineHeight: 28,
  },
  boxshadow: {},
  boxstyles: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 20,
    width: "100%",
  },
  dateBox: {
    paddingVertical: 5,
    borderRadius: 10,
    alignItems: "center",
    marginHorizontal: 6,
    width: 55,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  day: { fontSize: 16, fontFamily: "SourceSansPro_Regular" },
  mnthAndDate: {
    fontSize: 16,
    fontFamily: "SourceSansPro_SemiBold",
    color: "#000",
  },
  container: {
    marginVertical: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  optionContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 25,
  },
  radioOuter: {
    height: 26,
    width: 26,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#ccc",
    margin:4,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 3,
  },
  radioInner: {
    height: 12,
    width: 12,
    borderRadius: 6,
    backgroundColor: "#00AEEF",
  },

  gendarLabel: {
    marginLeft: 10,
    fontSize: 16,
    color: "#6D6D6D",
  },
  providerTxt: {
    fontSize: 16,
    fontFamily: "SourceSansPro_SemiBold",
    color: "#666",
    paddingLeft: 10,
  },
  timePeriodContainer: {
    paddingBottom: 20,
    paddingRight: 12,
    alignItems: "center",
  },
  timePeriodTxt: {
    fontSize: 18,
    fontFamily: "SourceSansPro_SemiBold",
    textAlign: "center",
    paddingBottom: 5,
  },
  timeSlotsBtn: {
    borderWidth: 0.2,
    borderColor: "#aaa",
    borderRadius: 3,
    elevation: 2,
    shadowOffset: { width: 1, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    width: isPlatformAndroid() ? 200 : 198,
    paddingVertical: 10,
  },
  timePeriodBtnTxt: {
    fontFamily: "SourceSansPro_SemiBold",
    fontSize: 15.5,
    textAlign: "center",
  },
  topContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingTop: 30,
    paddingBottom: 10,
  },
  selectTxt: { fontSize: 16, fontFamily: "SourceSansPro_SemiBold" },
  dateTxt: {
    fontSize: 16,
    fontFamily: "SourceSansPro_SemiBold",
    color: "#00c6ff",
  },
  calendar: {
    position: "absolute",
    top: 60,
    right: 10,
    width: 250,
    height: 280,
    backgroundColor: "#2470bd",
    overflow: "hidden",
    elevation: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    zIndex: 999,
  },
  previousTitleStyle: { color: "#fff", fontSize: 24 },
  nextTitleStyles: { color: "#fff", fontSize: 24 },
  calendarText: {
    marginTop: 10,
    textAlign: "center",
    color: "#fff",
    fontSize: 18,
    fontFamily: "SourceSansPro_Regular",
  },
  slot: {
    backgroundColor: "#fff",
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
    flex: 1,
    alignItems: "center",
    margin: 5,
    elevation: 2,
  },
  selectedSlot: {
    backgroundColor: "#00c6ff",
  },

  slotText: {
    fontSize: 16,
    color: "#000",
    fontFamily: "SourceSansPro_Regular",
  },
  selectedText: {
    color: "#fff",
  },
  disabledText: {
    color: "#aaa",
  },
  addMemberContainer: {
    alignItems: "center",
    marginVertical: 25,
    position: "absolute",
    bottom: 0,
    alignSelf: "center",
  },
  addMemberBtn: {
    borderWidth: 1,
    borderColor: "#00c6ff",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 25,
  },
  addMemberBtnTxt: {
    color: "#00c6ff",
    fontSize: 20,
    fontFamily: "SourceSansPro_SemiBold",
    paddingVertical: 10,
    paddingHorizontal: 50,
  },
  gridContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    paddingTop: 20,
  },
  slotBox: {
    width: "23%",
    margin: 3,
    borderRadius: 5,
    paddingVertical: 8,
    backgroundColor: "#fff",
    elevation: 2,
    justifyContent: "center",
    alignItems: "center",
    shadowOffset: { width: 1, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  dropDownBtn: { width: "100%", marginBottom: 30 },
  serviceBtn: { width: "100%" },
  timePeriodContainers: { flex: 1, maxHeight: 160, minHeight: 80 },
  calenderLoader:{justifyContent:"center",alignItems:"center",alignSelf:"center",paddingTop:25}
});